"use client";

import ActionGuide from "@/components/ActionGuide";
import type { ActionStep } from "@/types";
import { useRouter } from "next/navigation";

interface ActionGuideWrapperProps {
  actions: (ActionStep | string)[];
  confidenceScore: number;
}

export default function ActionGuideWrapper({
  actions,
  confidenceScore,
}: ActionGuideWrapperProps) {
  const router = useRouter();

  const handleDownload = () => {
    const cached = localStorage.getItem("lastScanResult");
    if (!cached) {
      alert("No scan result available to download.");
      return;
    }

    const result = JSON.parse(cached);
    const timestamp = new Date(result.created_at).toLocaleString();

    const report = [
      "TRUSTLENS AI — THREAT INTELLIGENCE REPORT",
      "=" .repeat(50),
      "",
      `Scan ID:      ${result.id}`,
      `Scan Type:    ${(result.scan_type || "unknown").toUpperCase()}`,
      `Timestamp:    ${timestamp}`,
      `Risk Score:   ${result.risk_score}%`,
      `Confidence:   ${result.confidence_score}%`,
      `Verdict:      ${result.verdict}`,
      `Category:     ${result.scam_category}`,
      "",
      "-".repeat(50),
      "INPUT SUMMARY",
      "-".repeat(50),
      result.input_summary || "N/A",
      "",
      "-".repeat(50),
      "AI EXPLANATION",
      "-".repeat(50),
      result.ai_explanation || "No AI explanation available.",
      "",
      "-".repeat(50),
      "THREAT INDICATORS",
      "-".repeat(50),
      ...(result.reasons && result.reasons.length > 0
        ? result.reasons.map((r: string, i: number) => `  ${i + 1}. ${r}`)
        : ["  No threat indicators detected."]),
      "",
      "-".repeat(50),
      "MATCHED PHRASES",
      "-".repeat(50),
      ...(result.matched_phrases && result.matched_phrases.length > 0
        ? result.matched_phrases.map((p: string) => `  - "${p}"`)
        : ["  None."]),
      "",
      "-".repeat(50),
      "DETECTED URLS",
      "-".repeat(50),
      ...(result.detected_urls && result.detected_urls.length > 0
        ? result.detected_urls.map((u: string) => `  - ${u}`)
        : ["  None."]),
      "",
      "-".repeat(50),
      "RECOMMENDED ACTIONS",
      "-".repeat(50),
      ...(result.recommended_actions && result.recommended_actions.length > 0
        ? result.recommended_actions.map((a: string | ActionStep, i: number) => {
            const text = typeof a === "string" ? a : `${a.title}: ${a.description}`;
            return `  ${i + 1}. ${text}`;
          })
        : ["  No actions recommended."]),
      "",
      "-".repeat(50),
      "THREAT BREAKDOWN",
      "-".repeat(50),
      ...(result.threat_breakdown && result.threat_breakdown.length > 0
        ? result.threat_breakdown.map((t: { layer: string; finding: string; severity: string; weight: number }) =>
            `  [${t.layer}] ${t.finding} (severity: ${t.severity}, weight: ${t.weight})`
          )
        : ["  No breakdown available."]),
      "",
      "-".repeat(50),
      "DETECTED CONTENT",
      "-".repeat(50),
      result.extracted_text || "  N/A",
      "",
      "=" .repeat(50),
      "Generated by TrustLens AI — Detect. Explain. Protect.",
      `Report generated at ${timestamp}`,
    ].join("\n");

    const blob = new Blob([report], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `trustlens-report-${result.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDismiss = () => {
    router.back();
  };

  return (
    <ActionGuide
      actions={actions}
      confidenceScore={confidenceScore}
      onDownload={handleDownload}
      onDismiss={handleDismiss}
    />
  );
}
